{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}
{{- end }}
